name: uhf_ura4_plugin
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path_android: "example/assets/romsis_logo.png"
  android: "launcher_icon"
  #android: true # can specify file name here e.g. "ic_launcher"
  adaptive_icon_background: "assets/white.png"  # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "#FFFFFF" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  
flutter:
  plugin:
    platforms:
      android:
        package: com.tagin.ura4_uhf_plugin.uhf_ura4_plugin
        pluginClass: UhfUra4Plugin
      ios:
        pluginClass: UhfUra4Plugin
      linux:
        pluginClass: UhfUra4Plugin
      macos:
        pluginClass: UhfUra4Plugin
      windows:
        pluginClass: UhfUra4PluginCApi
      web:
        pluginClass: UhfUra4PluginWeb
        fileName: uhf_ura4_plugin_web.dart


  # assets:
  #   - assets/romsis_logo.png
  # #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
